site_name: ksqlDB
site_url: https://docs.ksqldb.io
site_description: ksqlDB documentation
site_author: Confluent
copyright: Copyright &copy; 2019 <a href="https://www.confluent.io/">Confluent</a>.
# google_analytics: ['UA-27795084-5', 'mkdocs.org']

repo_url: https://github.com/confluentinc/ksql
edit_uri: ""
docs_dir: docs-md

theme:
    # name: mkdocs
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - xml
        - java
        - javascript
        - bash
        - json
        - properties
        - sql
        - scala

nav:
    - Home: index.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: JimGalasyn
        repo: ksqldb

plugins:
    - search
    - git-revision-date # Must come before the macros plugin    
    - macros

extra:
    site:
        # Product-related string tokens
        aktm: Apache Kafka®
        ak: Kafka
        c3short: Control Center
        c3: Confluent Control Center
        ccloud: Confluent Cloud
        ccloudent: Confluent Cloud Enterprise
        community: This is a community component of Confluent Platform.
        confluentcli: Confluent CLI
        cp: Confluent Platform
        crepfull: Confluent Replicator
        crep: Replicator
        crestlong: Confluent REST Proxy
        crest: REST Proxy
        cs: Confluent Server
        kcat: kafkacat
        kconnectlong: Kafka Connect
        kconnect: Connect
        ksqlui: preview KSQL web interface
        kstreams: Kafka Streams
        srccloud: Confluent Cloud Schema Registry
        srlong: Confluent Schema Registry
        sr: Schema Registry
        streaming: Event Streaming Platform
        zkfull: Apache ZooKeeper™
        zk: ZooKeeper

        # Build-related string tokens
        kafkaversion: 2.3
        kafkarelease: 5.3.1-ccs
        ksqldbversion: 0.6.0
        release: 5.3.1
        releasepostbranch: 5.3.1-post
        scalaversion: 2.12
        version: 5.3